#!/bin/bash
K_ID="$(~/.scripts/i3/mexec/.aux/keyboard_id.sh)"
xinput set-int-prop "$K_ID" "Device Enabled" 8 0 # disable keyboard
xdotool key F5                                   # press F5
xinput set-int-prop "$K_ID" "Device Enabled" 8 1 # enable keyboard
echo | dmenu -p "Press enter to return"     # wait for enter
exit 0


