#!/bin/sh
K_ID="$("$SCRIPTS"/i3/mexec/.aux/keyboard_id.sh)"
xinput set-int-prop "$K_ID" "Device Enabled" 8 0 # disable keyboard
xdotool type "!!"                                # type !!
xdotool key Return Return                        # run it
sleep 0.25
xinput set-int-prop "$K_ID" "Device Enabled" 8 1 # enable keyboard
~/.scripts/i3/mexec/.aux/read_keyboard.sh
exit 0


