-- local present, flit = pcall(require, "flit")
-- if not present then
-- 	return
-- end
--
-- flit.setup({
-- 	keys = { f = "f", F = "F", t = "t", T = "T" },
-- 	-- A string like "nv", "nvo", "o", etc.
-- 	labeled_modes = "v",
-- 	multiline = true,
-- 	-- Like `leap`s similar argument (call-specific overrides).
-- 	-- E.g.: opts = { equivalence_classes = {} }
-- 	opts = {},
-- })
