# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[preview]
max_width = 2000
max_height = 2000

[plugin]
prepend_previewers = [
  # markdown
  { name = "*.md", run = "glow" },
  # torrent
  { mime = "application/x-bittorrent", run = "torrent-preview" },
  # binary files
  { name = "*.{hex,bin}", run = "hexyl" },
  # archive
  { mime = "application/{,g}zip", run = "ouch" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", run = "ouch" },
]
