#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#############
## CONFIGS ##
#############

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.
bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 22	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer       false
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# Rules
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled

# # Start workspaces on the main monitor.
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc desktop '^1' --layout monocle

###############
## AUTOSTART ##
###############

xrandr --output eDP1 --mode 1366x768                # setting the default monitor modes
xrandr --output HDMI2 --off

xsetroot -cursor_name left_ptr                      # set the default mouse shape
xsetroot -solid "#000"                              # change background to solid black
synclient NaturalScrolling=1  VertScrollDelta=-111  # invert scrolling
synclient TapButton1=1                              # tap to click

xbacklight -set 50                                  # start with screen brightness at 50%

setxkbmap pt                                        # set keyboard map to portuguese
setxkbmap -option ctrl:nocaps                       # disables the caps lock key

"$HOME"/.config/polybar/launch.sh 					# Start status bar

killall "sxhkd"
sxhkd -m 1 &		                                # Bind keys with sxhkd

killall "dunst"
dunst &			                                    # dunst for notifications

killall "redshift"
redshift -c ~/.config/redshift/redshift.conf &      # start redshift
