#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#############
## CONFIGS ##
#############

bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 22	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer       false
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# Rules
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled

###############
## AUTOSTART ##
###############

$SCRIPTS/display.sh -o                              # start display and polybar

xsetroot -cursor_name left_ptr                      # set the default mouse shape
xsetroot -solid "#000"                              # change background to solid black
synclient NaturalScrolling=1  VertScrollDelta=-111  # invert scrolling
synclient TapButton1=1                              # tap to click

xbacklight -set 50                                  # start with screen brightness at 50%

setxkbmap pt                                        # set keyboard map to portuguese
setxkbmap -option ctrl:nocaps                       # disables the caps lock key

xmodmap -e 'keycode  248 = grave asciitilde grave asciitilde' # set special key [248] to keysym '~' [which is keybinded in sxhkd]

killall "sxhkd"
sxhkd -m 1 &		                                # Bind keys with sxhkd

killall "dunst"
dunst &			                                    # dunst for notifications

killall "redshift"
redshift -c ~/.config/redshift/redshift.conf &      # start redshift
