[default_view]

keymap = [
	{ keys = [ "T" ],			commands = ["new_tab"] },
	{ keys = [ "ctrl+t" ],		commands = ["new_tab"] },
	{ keys = [ "W" ],			commands = ["close_tab"] },
	{ keys = [ "ctrl+w" ],		commands = ["close_tab"] },
	{ keys = [ "q" ],			commands = ["close_tab"] },
	{ keys = [ "Q" ],			commands = ["quit --output-current-directory"] },

	{ keys = [ "R" ],			commands = ["reload_dirlist"] },
	{ keys = [ "z", "h" ],		commands = ["toggle_hidden"] },
	{ keys = [ "ctrl+h" ],		commands = ["toggle_hidden"] },
	{ keys = [ "\t" ],			commands = ["tab_switch 1"] },
	{ keys = [ "backtab" ],		commands = ["tab_switch -1"] },

	{ keys = [ "alt+1" ],		commands = ["tab_switch_index 1"] },
	{ keys = [ "alt+2" ],		commands = ["tab_switch_index 2"] },
	{ keys = [ "alt+3" ],		commands = ["tab_switch_index 3"] },
	{ keys = [ "alt+4" ],		commands = ["tab_switch_index 4"] },
	{ keys = [ "alt+5" ],		commands = ["tab_switch_index 5"] },

	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "arrow_left" ],	commands = ["cd .."] },
	{ keys = [ "arrow_right" ],	commands = ["open"] },
	{ keys = [ "\n" ],			commands = ["open"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	{ keys = [ "end" ],			commands = ["cursor_move_end"] },
	{ keys = [ "page_up" ],		commands = ["cursor_move_page_up"] },
	{ keys = [ "page_down" ],	commands = ["cursor_move_page_down"] },
	{ keys = [ "ctrl+u" ],  	commands = ["cursor_move_page_up 0.5"] },
	{ keys = [ "ctrl+d" ], 		commands = ["cursor_move_page_down 0.5"] },
	{ keys = ["ctrl+b"],		commands = ["cursor_move_page_up"] },
	{ keys = ["ctrl+f"], 		commands = ["cursor_move_page_down"] },

	# vim-like keybindings
	{ keys = [ "j" ],				commands = ["cursor_move_down"] },
	# There might be a way to do this automatically, but this works
	{ keys = [ "1", "j" ],			commands = ["cursor_move_down 1"] },
	{ keys = [ "2", "j" ],			commands = ["cursor_move_down 2"] },
	{ keys = [ "3", "j" ],			commands = ["cursor_move_down 3"] },
	{ keys = [ "4", "j" ],			commands = ["cursor_move_down 4"] },
	{ keys = [ "5", "j" ],			commands = ["cursor_move_down 5"] },
	{ keys = [ "6", "j" ],			commands = ["cursor_move_down 6"] },
	{ keys = [ "7", "j" ],			commands = ["cursor_move_down 7"] },
	{ keys = [ "8", "j" ],			commands = ["cursor_move_down 8"] },
	{ keys = [ "9", "j" ],			commands = ["cursor_move_down 9"] },
	{ keys = [ "1", "0", "j" ],		commands = ["cursor_move_down 10"] },
	{ keys = [ "1", "1", "j" ],		commands = ["cursor_move_down 11"] },
	{ keys = [ "1", "2", "j" ],		commands = ["cursor_move_down 12"] },
	{ keys = [ "1", "3", "j" ],		commands = ["cursor_move_down 13"] },
	{ keys = [ "1", "4", "j" ],		commands = ["cursor_move_down 14"] },
	{ keys = [ "1", "5", "j" ],		commands = ["cursor_move_down 15"] },
	{ keys = [ "1", "6", "j" ],		commands = ["cursor_move_down 16"] },
	{ keys = [ "1", "7", "j" ],		commands = ["cursor_move_down 17"] },
	{ keys = [ "1", "8", "j" ],		commands = ["cursor_move_down 18"] },
	{ keys = [ "1", "9", "j" ],		commands = ["cursor_move_down 19"] },
	{ keys = [ "2", "0", "j" ],		commands = ["cursor_move_down 20"] },
	{ keys = [ "2", "1", "j" ],		commands = ["cursor_move_down 21"] },
	{ keys = [ "2", "2", "j" ],		commands = ["cursor_move_down 22"] },
	{ keys = [ "2", "3", "j" ],		commands = ["cursor_move_down 23"] },
	{ keys = [ "2", "4", "j" ],		commands = ["cursor_move_down 24"] },
	{ keys = [ "2", "5", "j" ],		commands = ["cursor_move_down 25"] },
	{ keys = [ "2", "6", "j" ],		commands = ["cursor_move_down 26"] },
	{ keys = [ "2", "7", "j" ],		commands = ["cursor_move_down 27"] },
	{ keys = [ "2", "8", "j" ],		commands = ["cursor_move_down 28"] },
	{ keys = [ "2", "9", "j" ],		commands = ["cursor_move_down 29"] },
	{ keys = [ "3", "0", "j" ],		commands = ["cursor_move_down 30"] },
	{ keys = [ "k" ],				commands = ["cursor_move_up"] },
	# There might be a way to do this automatically, but this works
	{ keys = [ "1", "k" ],			commands = ["cursor_move_up 1"] },
	{ keys = [ "2", "k" ],			commands = ["cursor_move_up 2"] },
	{ keys = [ "3", "k" ],			commands = ["cursor_move_up 3"] },
	{ keys = [ "4", "k" ],			commands = ["cursor_move_up 4"] },
	{ keys = [ "5", "k" ],			commands = ["cursor_move_up 5"] },
	{ keys = [ "6", "k" ],			commands = ["cursor_move_up 6"] },
	{ keys = [ "7", "k" ],			commands = ["cursor_move_up 7"] },
	{ keys = [ "8", "k" ],			commands = ["cursor_move_up 8"] },
	{ keys = [ "9", "k" ],			commands = ["cursor_move_up 9"] },
	{ keys = [ "1", "0", "k" ],		commands = ["cursor_move_up 10"] },
	{ keys = [ "1", "1", "k" ],		commands = ["cursor_move_up 11"] },
	{ keys = [ "1", "2", "k" ],		commands = ["cursor_move_up 12"] },
	{ keys = [ "1", "3", "k" ],		commands = ["cursor_move_up 13"] },
	{ keys = [ "1", "4", "k" ],		commands = ["cursor_move_up 14"] },
	{ keys = [ "1", "5", "k" ],		commands = ["cursor_move_up 15"] },
	{ keys = [ "1", "6", "k" ],		commands = ["cursor_move_up 16"] },
	{ keys = [ "1", "7", "k" ],		commands = ["cursor_move_up 17"] },
	{ keys = [ "1", "8", "k" ],		commands = ["cursor_move_up 18"] },
	{ keys = [ "1", "9", "k" ],		commands = ["cursor_move_up 19"] },
	{ keys = [ "2", "0", "k" ],		commands = ["cursor_move_up 20"] },
	{ keys = [ "2", "1", "k" ],		commands = ["cursor_move_up 21"] },
	{ keys = [ "2", "2", "k" ],		commands = ["cursor_move_up 22"] },
	{ keys = [ "2", "3", "k" ],		commands = ["cursor_move_up 23"] },
	{ keys = [ "2", "4", "k" ],		commands = ["cursor_move_up 24"] },
	{ keys = [ "2", "5", "k" ],		commands = ["cursor_move_up 25"] },
	{ keys = [ "2", "6", "k" ],		commands = ["cursor_move_up 26"] },
	{ keys = [ "2", "7", "k" ],		commands = ["cursor_move_up 27"] },
	{ keys = [ "2", "8", "k" ],		commands = ["cursor_move_up 28"] },
	{ keys = [ "2", "9", "k" ],		commands = ["cursor_move_up 29"] },
	{ keys = [ "3", "0", "k" ],		commands = ["cursor_move_up 30"] },


	{ keys = [ "h" ],			commands = ["cd .."] },
	{ keys = [ "l" ],			commands = ["open"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],			commands = ["cursor_move_end"] },
	{ keys = [ "r" ],			commands = ["open_with"] },

	{ keys = [ "H" ],			commands = ["cursor_move_page_home"] },
	{ keys = [ "L" ],			commands = ["cursor_move_page_middle"] },
	{ keys = [ "M" ],			commands = ["cursor_move_page_end"] },

	{ keys = [ "[" ],			commands = ["parent_cursor_move_up"] },
	{ keys = [ "]" ],			commands = ["parent_cursor_move_down"] },

	{ keys = [ "c", "d" ],		commands = [":cd "] },
	{ keys = [ "d", "d" ],		commands = ["cut_files"] },
	{ keys = [ "y", "y" ],		commands = ["copy_files"] },
	{ keys = [ "y", "n" ],		commands = ["copy_filename"] },
	{ keys = [ "y", "." ],		commands = ["copy_filename_without_extension"] },
	{ keys = [ "y", "p" ],		commands = ["copy_filepath"] },
	{ keys = [ "y", "d" ],		commands = ["copy_dirpath"] },

	{ keys = [ "delete" ],		commands = ["delete_files"] },
	{ keys = [ "d", "D" ],		commands = ["delete_files"] },

	{ keys = [ "p", "p" ],		commands = ["paste_files"] },
	{ keys = [ "p", "o" ],		commands = ["paste_files --overwrite=true"] },

	{ keys = [ "a" ],			commands = ["rename_append"] },
	{ keys = [ "A" ],			commands = ["rename_prepend"] },

	{ keys = [ "f", "t" ],		commands = [":touch "] },

	{ keys = [ " " ],			commands = ["select --toggle=true"] },
	{ keys = [ "t" ],			commands = ["select --all=true --toggle=true"] },

	{ keys = [ "w" ],			commands = ["show_tasks --exit-key=w"] },
	{ keys = [ "b", "b" ],		commands = ["bulk_rename"] },
	{ keys = [ "=" ],			commands = ["set_mode"] },

	{ keys = [ ":" ],			commands = [":"] },
	{ keys = [ ";" ],			commands = [":"] },

	# { keys = [ "'" ],			commands = [":shell "] },
	# { keys = [ "m", "k" ],		commands = [":mkdir "] },
	# { keys = [ "c", "w" ],		commands = [":rename "] },

	{ keys = [ "/" ],			commands = [":search "] },
	{ keys = [ "|" ],			commands = [":search_inc "] },
	{ keys = [ "\\" ],			commands = [":search_glob "] },
	{ keys = [ "S" ],			commands = ["search_fzf"] },
	{ keys = [ "C" ],			commands = ["subdir_fzf"] },

	{ keys = [ "n" ],			commands = ["search_next"] },
	{ keys = [ "N" ],			commands = ["search_prev"] },

	{ keys = [ "s", "r" ],		commands = ["sort reverse"] },
	{ keys = [ "s", "l" ],		commands = ["sort lexical"] },
	{ keys = [ "s", "m" ],		commands = ["sort mtime"] },
	{ keys = [ "s", "n" ],		commands = ["sort natural"] },
	{ keys = [ "s", "s" ],		commands = ["sort size"] },
	{ keys = [ "s", "e" ],		commands = ["sort ext"] },

	{ keys = [ "g", "r" ],		commands = ["cd /"] },
	{ keys = [ "g", "c" ],		commands = ["cd ~/.config"] },
	{ keys = [ "g", "d" ],		commands = ["cd ~/Downloads"] },
	{ keys = [ "g", "e" ],		commands = ["cd /etc"] },
	{ keys = [ "g", "h" ],		commands = ["cd ~/"] },
	{ keys = [ "?" ],			commands = ["help"] },

	# custom paths
	{ keys = ["g", "w"],		commands = ["cd ~/GBT/GBT_Project"] },
	{ keys = ["g", "p"], 		commands = ["cd ~/Personal_Project"] },
	{ keys = ["g", "s"], 		commands = ["cd ~/.scripts"] },
	{ keys = ["g", "m"], 		commands = ["cd ~/Music"] },
	{ keys = [ "D", "e" ],		commands = ["spawn /home/dedukun/.scripts/joshuto/dragon-drop.sh -e %s"] },
	{ keys = [ "D", "t" ],		commands = ["spawn /home/dedukun/.scripts/joshuto/dragon-drop.sh -t"] },

	# bookmark
	{ keys = [ "m" ],		commands = ["add_bookmark"] },
	{ keys = [ "'" ],		commands = ["cd_bookmark"] },
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	{ keys = [ "end" ],			commands = ["cursor_move_end"] },

	# vim-like keybindings
	{ keys = [ "j" ],			commands = ["cursor_move_down"] },
	{ keys = [ "k" ],			commands = ["cursor_move_up"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],			commands = ["cursor_move_end"] },

	{ keys = [ "w" ],			commands = ["show_tasks"] },
	{ keys = [ "escape" ],		commands = ["show_tasks"] },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	{ keys = [ "end" ],			commands = ["cursor_move_end"] },

	# vim-like keybindings
	{ keys = [ "j" ],			commands = ["cursor_move_down"] },
	{ keys = [ "k" ],			commands = ["cursor_move_up"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],			commands = ["cursor_move_end"] },

	{ keys = [ "w" ],			commands = ["show_tasks"] },
	{ keys = [ "escape" ],		commands = ["show_tasks"] },
]
